domains:
- fungi
- archaea
#- bacteria
- viral
#- invertebrate
#- plant
- protozoa
#- vertebrate_mammalian
#- vertebrate_other
## only for genbank
#- metagenomes
#- other

# top level directory precomputed signatures
sig_location: /data/wort/wort-genomes/sigs

# ksizes to build the databases for
db_ksizes:
- 21
- 31
- 51

# options: genbank, refseq
db:
- refseq
#- genbank

# bloom filter sizes for SBTs
bfsize:
- 1e4
- 1e5
- 1e6
